-- users.sql
GRANT USAGE ON SCHEMA seqdb TO seqdb_authenticate;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA seqdb TO seqdb_authenticate;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA seqdb TO seqdb_authenticate;
ALTER DEFAULT PRIVILEGES IN SCHEMA seqdb GRANT ALL PRIVILEGES ON TABLES TO seqdb_authenticate;

