-- users.sql
GRANT USAGE ON SCHEMA dina_sch TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA dina_sch TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dina_sch TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA dina_sch GRANT ALL PRIVILEGES ON TABLES TO app_user;

CREATE ROLE migr_role NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'changeme2';
GRANT CONNECT ON DATABASE dina_db TO migr_role;
GRANT USAGE, CREATE ON SCHEMA dina_sch TO migr_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA dina_sch GRANT ALL PRIVILEGES ON TABLES TO migr_role;

ALTER DEFAULT PRIVILEGES FOR USER migr_role IN SCHEMA dina_sch GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES FOR USER migr_role IN SCHEMA dina_sch GRANT SELECT, USAGE ON SEQUENCES TO app_user;
