CREATE SCHEMA objectstore;
GRANT USAGE ON SCHEMA objectstore TO test;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA objectstore TO test;
ALTER DEFAULT PRIVILEGES IN SCHEMA objectstore GRANT ALL PRIVILEGES ON TABLES TO test;