= Object Storage

== MinIO

The Object Store module uses https://min.io/[MinIO] as a storage abstraction layer.

== Object Metadata

The Object Store workflow consists of the upload of an object (a file) and then the submission of the associated metadata. Some data available at the upload stage should be preserved and transfered to the associated metadata once the latter is submitted. For example: the original filename, the hash of the file, the received media type, the detected media type ...

== MinIO Metadata

MinIO Java client supports `headerMap` in the http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.io.InputStream-java.lang.Long-java.util.Map-io.minio.ServerSideEncryption-java.lang.String-[putObject] method as a mechanism to store metadata associated with an object. Even if this method works in most of the cases it has 2 main disadvantages:

. The metadata has to be known before we start uploading the object binaries and can not be changed later (it would require to copy the object into a new object with a different name).
. The metadata is stored in an hidden file managed by MinIO making it less explicit and potentially risky.

Object tagging is not supported by MinIO: https://github.com/minio/minio/issues/5896[Issue 5896]

== Custom Object Metadata

So in order to offer more flexibility the Object Store stores its own metadata file next to the object being stored. The metadata file has the same name (an UUID) as the object + a `_meta.json` suffix. The custom metadata file is a simple json document and contains a version number so it could evolve without having to rewrite all the meta files. The metadata file is NOT a replacement for the metadata database offered by the Object Store. The metadata file is used to capture upload time data that is then copied in the metadata database entry. The metadata file is preserved even after the metadata database entry is created as an immutable file representing the data used to create the record.